# Generated by Django 4.1.5 on 2023-02-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_rename_typeitem_item_type_item_alter_item_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estoque.estoque'),
        ),
    ]
