  version: "3.3"

  services:
    estoque:
      build: .
     
      command: /bin/bash  -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./api:/app
      ports:
        - 8000:8000
      depends_on:
        - db

      networks:
        - backend
    db:
      build: ./api/db/
      environment:
        - PGDATABASE=estoque
        - POSTGRES_USER=api
        - POSTGRES_PASSWORD=api
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      networks:
        - backend
      
  volumes:
    postgres_data:

  networks:
    backend: